//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioTech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public int id_livre { get; set; }
        public string titre { get; set; }
        public string isbn { get; set; }
        public System.DateTime date_publication { get; set; }
        public int id_auteur { get; set; }
    
        public virtual Auteur Auteur { get; set; }
    }
}
